name: Lean Action CI

on:
  push:
    paths-ignore:
      - 'blueprint/**'
      - '.github/workflows/blueprint.yml'
      - '.github/workflows/pages-static.yml'
  pull_request:
    paths-ignore:
      - 'blueprint/**'
      - '.github/workflows/blueprint.yml'
      - '.github/workflows/pages-static.yml'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: leanprover/lean-action@v1
      - uses: leanprover-community/docgen-action@v1
