name: Lean Action CI

on:
  push:
    paths:
      - 'LeanTopology/**'
      - '*.lean'
      - 'lakefile.toml'
      - 'lake-manifest.json'
      - 'lean-toolchain'
      - '.github/workflows/lean_action_ci.yml'
  pull_request:
    paths:
      - 'LeanTopology/**'
      - '*.lean'
      - 'lakefile.toml'
      - 'lake-manifest.json'
      - 'lean-toolchain'
      - '.github/workflows/lean_action_ci.yml'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: leanprover/lean-action@v1
      - uses: leanprover-community/docgen-action@v1
